// lib/mock-data.ts
import { Property } from '../types/property';

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Modern Waterfront Villa',
    description: 'Experience luxury living at its finest in this stunning waterfront villa. Featuring floor-to-ceiling windows, an infinity pool, and direct beach access. The open-concept design seamlessly blends indoor and outdoor living, perfect for entertaining.',
    price: 4500000,
    currency: 'USD',
    location: {
      address: '123 Ocean Drive',
      city: 'Miami Beach',
      state: 'FL',
      zipCode: '33139',
      coordinates: { lat: 25.7907, lng: -80.1300 },
    },
    bedrooms: 5,
    bathrooms: 6,
    squareFeet: 5200,
    lotSize: 0.5,
    yearBuilt: 2021,
    propertyType: 'villa',
    listingType: 'sale',
    status: 'active',
    amenities: ['Infinity Pool', 'Private Beach', 'Smart Home', 'Wine Cellar', 'Home Theater', 'Gym', 'Guest House'],
    images: [
      { url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80', alt: 'Exterior' },
      { url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80', alt: 'Living Room' },
      { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80', alt: 'Kitchen' },
    ],
    virtualTourUrl: 'https://example.com/tour/1',
    agentId: 'agent-1',
    features: {
      parking: 4,
      pool: true,
      gym: true,
      smartHome: true,
      waterfront: true,
    },
    isFeatured: true,
    isLuxury: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Penthouse with City Views',
    description: 'Spectacular penthouse offering panoramic views of the city skyline. This residence features premium finishes, a private elevator, and expansive terraces perfect for outdoor living.',
    price: 3200000,
    currency: 'USD',
    location: {
      address: '456 Park Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10022',
      coordinates: { lat: 40.7589, lng: -73.9772 },
    },
    bedrooms: 3,
    bathrooms: 3.5,
    squareFeet: 2800,
    yearBuilt: 2019,
    propertyType: 'penthouse',
    listingType: 'sale',
    status: 'active',
    amenities: ['Concierge', 'Private Elevator', 'Terrace', 'Gym', 'Parking', 'Storage'],
    images: [
      { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80', alt: 'View' },
      { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80', alt: 'Interior' },
    ],
    agentId: 'agent-2',
    features: {
      parking: 2,
      gym: true,
      view: 'City Skyline',
    },
    isFeatured: true,
    createdAt: '2024-01-14T10:00:00Z',
    updatedAt: '2024-01-14T10:00:00Z',
  },
  {
    id: '3',
    title: 'Contemporary Hillside Estate',
    description: 'Architectural masterpiece nestled in the Hollywood Hills. This gated estate offers ultimate privacy with stunning views, a infinity pool, and smart home technology throughout.',
    price: 8500000,
    currency: 'USD',
    location: {
      address: '789 Mulholland Drive',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90046',
      coordinates: { lat: 34.1203, lng: -118.3305 },
    },
    bedrooms: 6,
    bathrooms: 8,
    squareFeet: 8500,
    lotSize: 1.2,
    yearBuilt: 2020,
    propertyType: 'house',
    listingType: 'sale',
    status: 'active',
    amenities: ['Infinity Pool', 'Home Theater', 'Wine Cellar', 'Gym', 'Guest House', 'Smart Home', 'Gated Entry'],
    images: [
      { url: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80', alt: 'Exterior' },
      { url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80', alt: 'Pool' },
    ],
    virtualTourUrl: 'https://example.com/tour/3',
    agentId: 'agent-3',
    features: {
      parking: 6,
      pool: true,
      gym: true,
      smartHome: true,
    },
    isLuxury: true,
    openHouse: {
      date: '2024-02-01',
      startTime: '14:00',
      endTime: '17:00',
    },
    createdAt: '2024-01-13T10:00:00Z',
    updatedAt: '2024-01-13T10:00:00Z',
  },
  // Add more mock properties as needed
];